version: "3.9"

services:
  generator:
    container_name: generator
    build:
      context: ./generator/
      dockerfile: Dockerfile
    depends_on:
      - driver
    volumes:
      - ./generator:/app
    networks:
      - uklon-network
  driver:
    container_name: driver_geo
    build:
      context: ./driver_app/
      dockerfile: Dockerfile
    environment:
      FLASK_ENV: "production"
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    volumes:
      - ./driver_app:/app
    networks:
      - uklon-network
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_DB: "uklon-test"
      POSTGRES_USER: "uklon"
      POSTGRES_PASSWORD: "test"
      PGDATA: /data/postgres
    volumes:
      - postgres-db:/data/postgres
    ports:
      - "5452:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U uklon -d uklon-test"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: always
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
    networks:
      - uklon-network

volumes:
  postgres-db:
    driver: local

networks:
  uklon-network:
    driver: bridge